name: DockerPush
on: push

jobs:
  publish:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install npm dependencies
        run: npm i

      - name: Release
        run: npm run docker:push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
